name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip freeze > requirements.txt
        pip install -r requirements.txt

    - name: Run tests
      run: |
        ppython app.py

